name: PR Auto Approve & Merge

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-approve:
    if: github.event.pull_request.user.login == 'vickyliin'
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GH_VERA_PAT }}

  auto-merge:
    if: github.event.pull_request.user.login == 'vera0409'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GH_VERA_PAT }}
          GH_REPO: ${{ github.repository }}
